name: manipalleaks
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^6.0.16
  path_provider: ^1.6.11
  flutter_launcher_icons: ^0.7.5
  cupertino_icons: ^0.1.3
  table_calendar: ^2.2.3
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.4.10
  curved_navigation_bar: ^0.3.2
  flutter_icons: ^1.1.0
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  flutter_linkify: ^3.1.3
  flutter_share: ^1.0.2+1
  share: ^0.6.4+3
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6
  image_cropper: ^1.2.3
  cached_network_image: ^2.2.0+1
  webview_flutter: ^0.3.22+1
  google_fonts: ^1.1.0
  clay_containers: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/shuvam logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
